require('dotenv').config();
const express=require('express');const path=require('path');const multer=require('multer');
const fs=require('fs');const app=express();const PORT=process.env.PORT||3000;
const upload=multer({dest:path.join(__dirname,'uploads'),limits:{fileSize:10*1024*1024}});
fs.mkdirSync(path.join(__dirname,'uploads'),{recursive:true});app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
async function openAI(body){if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is not configured on the server.');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'OpenAI request failed');return d;}
app.post('/api/chat',async(req,res)=>{try{const messages=Array.isArray(req.body.messages)?req.body.messages:[];const d=await openAI({model:process.env.OPENAI_MODEL||'gpt-5-mini',instructions:'You are G ONE AI, a friendly advanced assistant. Match Hindi, Hinglish, or English. Be clear and helpful.',input:messages});res.json({reply:d.output_text||'No response generated.'});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/search',async(req,res)=>{try{const q=String(req.query.q||'').trim();if(!q)return res.status(400).json({error:'Query is required.'});if(!process.env.BRAVE_SEARCH_API_KEY)return res.status(500).json({error:'BRAVE_SEARCH_API_KEY is not configured on the server.'});const r=await fetch('https://api.search.brave.com/res/v1/web/search?q='+encodeURIComponent(q),{headers:{Accept:'application/json','X-Subscription-Token':process.env.BRAVE_SEARCH_API_KEY}});const d=await r.json();if(!r.ok)return res.status(r.status).json(d);res.json({results:(d.web?.results||[]).map(x=>({title:x.title,snippet:x.description||'',url:x.url}))});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/file',upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'No file uploaded.'});const ext=path.extname(req.file.originalname).toLowerCase();let text='';if(ext==='.txt'||ext==='.md'||ext==='.csv'||ext==='.json'){text=fs.readFileSync(req.file.path,'utf8');}else if(ext==='.pdf'){try{const pdfParse=require('pdf-parse');text=(await pdfParse(fs.readFileSync(req.file.path))).text;}catch(e){return res.status(500).json({error:'PDF support needs the pdf-parse package. Run npm install.'});}}else return res.status(400).json({error:'Supported files: TXT, MD, PDF, CSV, JSON.'});fs.unlinkSync(req.file.path);res.json({name:req.file.originalname,text:text.slice(0,100000)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/vision',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'No image uploaded.'});if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is not configured on the server.');const mime=req.file.mimetype;const b64=fs.readFileSync(req.file.path).toString('base64');const d=await openAI({model:process.env.OPENAI_VISION_MODEL||process.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'user',content:[{type:'input_text',text:'Analyze this image and explain what you see clearly.'},{type:'input_image',image_url:`data:${mime};base64,${b64}`}]}]});fs.unlinkSync(req.file.path);res.json({reply:d.output_text||'Image analyzed.'});}catch(e){if(req.file)try{fs.unlinkSync(req.file.path)}catch{}res.status(500).json({error:e.message});}});
app.listen(PORT,()=>console.log(`G ONE AI running on http://localhost:${PORT}`));
